spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stephene-bernardo/config-server
          search-paths: config
        default-label: main
server:
  port: 8888