server:
  port: 8761
sample:
  text: hi did i work!!!
  secretText: '{cipher}AQA8or0ZMbD0dJvdZCIRLUP/uGNfkOTwaG6BZ50D+jczC2Z4AndpwsWF+eKTivEYHntA5t2CE0LHnhwG8nskbDBzh+Wr5xZjxEvfkPR117WyxghxFss1v/PxwTN++FHmpUABQeEPzoGO8f0A7MRuiAns/oALvYXfOgnmsPBkefySxBjkIf5VqVEojbIUQ9l5VQspPZ90f/XoQC1Erky/zs9C00g9oEB1P/OfKFi7sxX51uWSv00DvcMsW/u4B7wOdSSELYvirk4CfypOwQA+E2cGbqNjAmnKueAc4KyPP8lT1ZOOAvCsi7BGi0C24swgMG0WacQvuyZTL8x7tNEPAOqGiGMRu1FAg6dDtChpqA9x6Xl4gw8Od6CIFJoalN7GOBs='