server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      enable-self-preservation: false
      waitTimeInMsWhenSyncEmpty: 0
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
sample:
  text: hi did i work!!!
  secretText: '{cipher} 6092AQA9A89NpT6UkGVaSESip7Yiq6xul9ZzcvRZIZ8spbWhxmvHTlr3vkmvGpZx0gn4rwwcoX3LdRLTty8g5Xfz4Yvw5BowLAzi/F9QVIL8y+SnEUrpEqns+V2dqUY83MAlDraT0ykLn9TH9hko37IXytMtrPrqbknbwgGXBr8cGxwsbvXaWmprOeepL7AJ8tRoXpIZyZjAMHX8oM55RokOV9i7qTvSfBbctfenjNeHwK/rH4P2aJPy7vSI9Q8jt8bp5lhD9524NqouWij5qdZ1N8cJC8aBZbGSAIMsiope3XQWaL7TWnzqf9ZoP7SChpqtffQ/iNf+NhsA//iTd2QBumpg6qjK+yFsd0e8g0ovchnseSZdLiWVmXF6gMMcB1/lnjA='