server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      enable-self-preservation: false
      waitTimeInMsWhenSyncEmpty: 0
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
sample:
  text: hi did i work!!!
  secretText: '{cipher} AQAR9Lpj+XNgWM7RtMQX/gu8R1Ds+bGRXFQYq8ujv1+9wk20dVXV9q4sGB9NkQ5FzeNGdySrNIQHkvWnqKlWSQRtWXUhPYjGh45H/n3OrzzgEQZKk9owlWiCcsfjPe9rEadjWJcTvfQaJ9dtg5rTKaMOKNfSqSn86Nt5knoUPfU+dBT+iXGR4UaXO5hc4xfHn8l7I2QzlA1V14vnCXkYiKH41cJu+OWeXNVJ1G+zhmJWcW+ngxAh6Vv9VLt8OlUoPJAA9hSLemzWh63jwKdj/R7pmEM51B9KWLtgNAK4M6cslutPfY5+Rh3wD4I9UB9PSUP1V0FU1oI8MQTxpv41nUUaJhN877H1yCeMzWxAZbtEgNj2Ol1FIBKUwwyuM0KHWd5ssa+0A+8z3L9XHSTVO26GelPuJM6qS9cH/X20h222gw=='